# apiVersion: v1
# kind: Service
# metadata:
#   name: cc-audit
#   namespace: cc-dev
#   labels:
#     app: cc
# spec:
#   type: NodePort
#   ports:
#     # the port that this service should serve on
#   - port: 8803
#     targetPort: 8803
#     nodePort: 32203
#   selector:
#     app: cc
#     name: cc-audit
# ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cc-audit
  namespace: cc-dev
  labels:
    app: cc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cc
        name: cc-audit
    spec:
      containers:
      - name: cc-audit
        image: ihub.helium.io:30100/console/cc-audit:16.0.0.rc1
        imagePullPolicy: Always
        env:
        - name: CONFIG_SERVER_HOST
          value: cc-config-server
        - name: CONFIG_SERVER_PORT
          value: "8825"
        - name: CONFIG_SERVER_USERNAME
          value: admin
        - name: CONFIG_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: security-password
              name: config-server-secret
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.3"
            memory: "1Gi"
        ports:
        - containerPort: 8803

# - name: "K8S_FILTERED_NAMESPACES"
#   value: "default,kube-system"
# - name: "RABBITMQ_HOST"
#   value: "cc-rabbitmq"
# - name: "RABBITMQ_PORT"
#   value: "5672"
# - name: "RABBITMQ_USERNAME"
#   value: "admin"
# - name: "RABBITMQ_PASSWORD"
#   value: "enn123456"
# - name: "MYSQL_HOST"
#   value: "cc-mysql"
# - name: "MYSQL_PORT"
#   value: "3306"
# - name: "MYSQL_USERNAME"
#   value: "root"
# - name: "MYSQL_PASSWORD"
#   value: "root"
# - name: "ELASTICSEARCH_HOST"
#   value: "http://10.19.140.200:31921/cc"
  # elasticsearch-client.monitor-essential-service:9200
# - name: "ACCOUNT_URL"
#   value: "http://10.19.140.200:32210/gw/ac/api/v1"
  # cc-gateway:8810
# - name: "spring_profiles_active"
#   value: "prod"