apiVersion: v1
kind: Service
metadata:
  name: connector-ui
  namespace: xin-ao
  labels:
    app: connector-ui
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 4205
    targetPort: 4205
    nodePort: 30425
  selector:
    app: connector-ui
    name: connector-ui
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: connector-ui
  namespace: xin-ao
  labels:
    app: connector-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: connector-ui
        name: connector-ui
    spec:
      containers:
      - name: connector-ui
        image: ihub.helium.io:29006/library/connector-ui:2018.05.30
        imagePullPolicy: Always
        env:
        - name: "CONNECTOR_URL"
          value: "http://10.19.248.200:30818"
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.3"
            memory: "1Gi"
        ports:
        - containerPort: 4205
