# apiVersion: v1
# kind: Service
# metadata:
#   name: cc-log
#   namespace: song
#   labels:
#     app: cc
# spec:
#   type: NodePort
#   ports:
#     # the port that this service should serve on
#   - port: 8814
#     targetPort: 8814
#   selector:
#     app: cc
#     name: cc-log
# ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cc-log
  namespace: song
  labels:
    app: cc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cc
        name: cc-log
    spec:
      containers:
      - name: cc-log
        image: 127.0.0.1:29006/song/cc-log:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: "ES_HOST"
          value: "10.19.140.200"
        - name: "ES_PORT"
          value: "29400"
        - name: "ES_USERNAME"
          value: "elastic"
        - name: "ES_PASSWORD"
          value: "changeme"
        - name: "KUBELET_TABLE_NAME"
          value: "kubelet*"
        - name: "KUBE_PROXY_TABLE_NAME"
          value: "kubeproxy*"
        - name: "FLANNELD_TABLE_NAME"
          value: "flanneld*"
        - name: "CLUSTER_PREFIX"
          value: "sh_test"
        - name: "spring_profiles_active"
          value: "prod"
        resources:
          limits:
            cpu: "0.3"
            memory: "1Gi"
          requests:
            cpu: "0.3"
            memory: "1Gi"
        ports:
        - containerPort: 8814