# apiVersion: v1
# kind: Service
# metadata:
#   name: cc-metric
#   namespace: song
#   labels:
#     app: cc
# spec:
#   type: NodePort
#   ports:
#     # the port that this service should serve on
#   - port: 8813
#     targetPort: 8813
#   selector:
#     app: cc
#     name: cc-metric
# ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cc-metric
  namespace: song
  labels:
    app: cc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cc
        name: cc-metric
    spec:
      containers:
      - name: cc-metric
        image: ihub.helium.io:29006/song/cc-metric
        imagePullPolicy: Always
        env:
        - name: "OPENTSDB_URL"
          value: "http://10.19.138.169:4242/api"
        - name: "MYSQL_HOST"
          value: "10.19.138.166"
        - name: "MYSQL_PORT"
          value: "3306"
        - name: "MYSQL_USERNAME"
          value: "root"
        - name: "MYSQL_PASSWORD"
          value: "song"
        - name: "spring_profiles_active"
          value: "prod"
        resources:
          limits:
            cpu: "0.3"
            memory: "2Gi"
          requests:
            cpu: "0.3"
            memory: "1Gi"
        ports:
        - containerPort: 8803