apiVersion: v1
kind: PersistentVolume
metadata:
  name: pre1-kafkautils
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  cephfs:
    monitors:
    - 10.19.137.144:6789
    - 10.19.137.145:6789
    - 10.19.137.146:6789
    path: /k8s/cc-dev/pre1-kafkautils-data
    secretRef:
      name: ceph-secret-jsonnet
    user: admin
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pre1-kafkautils-data
    namespace: cc-dev
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pre1-kafka1log
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  cephfs:
    monitors:
    - 10.19.137.144:6789
    - 10.19.137.145:6789
    - 10.19.137.146:6789
    path: /k8s/cc-dev/pre1-kafka1log-data
    secretRef:
      name: ceph-secret-jsonnet
    user: admin
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pre1-kafka1log-data
    namespace: cc-dev
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pre1-kafka2log
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  cephfs:
    monitors:
    - 10.19.137.144:6789
    - 10.19.137.145:6789
    - 10.19.137.146:6789
    path: /k8s/cc-dev/pre1-kafka2log-data
    secretRef:
      name: ceph-secret-jsonnet
    user: admin
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pre1-kafka2log-data
    namespace: cc-dev
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pre1-kafka3log
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  cephfs:
    monitors:
    - 10.19.137.144:6789
    - 10.19.137.145:6789
    - 10.19.137.146:6789
    path: /k8s/cc-dev/pre1-kafka3log-data
    secretRef:
      name: ceph-secret-jsonnet
    user: admin
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pre1-kafka3log-data
    namespace: cc-dev
  persistentVolumeReclaimPolicy: Retain