# apiVersion: v1
# kind: Service
# metadata:
#   name: sighting
#   namespace: song
#   labels:
#     app: sighting
# spec:
#   type: NodePort
#   ports:
#     # the port that this service should serve on
#   - port: 4206
#     targetPort: 4206
#   selector:
#     app: sighting
#     name: sighting
# ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sighting
  namespace: song
  labels:
    app: sighting
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sighting
        name: sighting
    spec:
      containers:
      - name: sighting
        image: ihub.helium.io:29006/song/sighting:v0.1
        imagePullPolicy: Always
        env:
        - name: "METRIC_URL"
          value: "http://10.19.140.200:29206/api/v1"
        - name: "LOG_URL"
          value: "http://10.19.140.200:31360/api/v1"
        - name: "cluster_name"
          value: "shanghai"
        resources:
          limits:
            cpu: "0.3"
            memory: "2Gi"
          requests:
            cpu: "0.3"
            memory: "1Gi"
        ports:
        - containerPort: 4206
